spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
        - id: service
          uri: lb://service
          predicates:
            - Path=/api/service/**
        - id: service3
          uri: lb://service3
          predicates:
            - Path=/api/service3/**
management:
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka