spring:
  application:
    name: service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8095
management:
  tracing:
    sampling:
      probability: 1.0